//sa se det dak este prim sa8u nu
#include<iostream.h>
int prim(int n);
int pp(int p);

void main ()
{int  k;
cou<<"k=";cin>>k;
	cout<<k<<"este prim cu ="<<prim(n);

                                       }

int pp(int p)
{int i;j=0,v;
for(i=100;i<=1000;i++)
	if((int)sqrt(i)==sqrt(i))
	      {j++;v[j]=i;}



int prim(int n);
{int k,i;
cout<<"k=";cin>>k;
for(i=1;i<=n/2;i++)
	if(v[i]%k==0)
	  return v[i];
